"""remove updated_at and add create_at in table Players

Revision ID: 24a7bacf6dc6
Revises: e1116efb159d
Create Date: 2023-09-16 21:21:05.370509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24a7bacf6dc6'
down_revision = 'e1116efb159d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('players', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('players', 'created_at')
    # ### end Alembic commands ###
